version: "3"

services:
  api:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DBNAME=product_db
      - MYSQL_USER=ola
      - MYSQL_PASSWORD=mindbender
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./product_db.sql:/docker-entrypoint-initdb.d/product_db.sql
    command:
      ["mysqld", "--init-file=/docker-entrypoint-initdb.d/product_db.sql"]
