version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'product_db'
      MYSQL_USER: 'ola'
      MYSQL_PASSWORD: 'mypass'
      MYSQL_ROOT_PASSWORD: 'mypassword'
    ports:
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'
      - './scripts:/docker-entrypoint-initdb.d/' # add this line to mount the directory containing the script

  php:
    build: .
    restart: always
    ports:
      - '8000:80'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: 'product_db'
      DB_USER: 'root'
      DB_PASSWORD: ''
